name: Generate Pacman Graph

permissions:
  contents: write

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate SVG
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: thesakshikendre
          outputs: |
            pacman-contribution-graph.svg
            pacman-contribution-graph-dark.svg?palette=github-dark

      - name: Commit & Push
        run: |
          mkdir -p dist
          mv *.svg dist/
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add dist
          git commit -m "Generate Pacman graph"
          git push
